### ISSUE TITLE
Aymmetric Encryption

### ISSUE THREAD

**Issue by deltaghost101** [andreas-gone-wild/snackis#1]
"Snackis delegates anything concerning encryption to libsodium. The IETF-variant of ChaCha20-Poly1305 is used to encrypt the master password and database, while XSalsa20 is used for everything else. The master password is hashed using Scrypt, and encrypted using the hash as key for future validation." 
Do you mean that Alice can encrypt a message to Bob using symmetric key algorithm  in Snackis.
(Or in other words Alice and Bobs communication is encrypted via symmetric algorithms)
If that is so then how is the pre shared key(PSK) negotiated or exchanged between the two users.
Do you use asymmetric crypto to share the symmetric key ? Can you elaborate more on the encryption scheme used by Snackis .

**Comment by andreas-gone-wild** [comment]
Everything but the database, including messages, is asymmetric; using XSalsa20. The only thing that is shared is the public key.

**Comment by deltaghost101** [comment]
But XSalsa20 is symmetric stream cipher , what asymmetric algorithm do you use ?

**Comment by andreas-gone-wild** [comment]
libsodiums default, X25519.
